name: Gradle Wrapper Validation

on: [ push, pull_request ]

jobs:
  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
